__productname__ = 'qgh'
__version__ = '1.0'
__author__ = 'infyhr'
__author_email__ = 'infy@cybershade.org'
__description__ = 'Console curses browser for github repo contents'
__url__ = 'https://github.com/infyhr/qgh'
__license__ = 'MIT'